apiVersion: extensions/v1beta1 # this will become 'apps/v1' after kubernetes 1.9 release. See (https://kubernetes.io/docs/reference/workloads-18-19/)
kind: Deployment
metadata:
  name: redis-master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        role: master
        tier: backend
    spec:
      containers:
      - name: master
        image: redis # or 'long way: k8s.gcr.io/redis:e2e'
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379