apiVersion: extensions/v1beta1 # this will become 'apps/v1' after kubernetes 1.9 release. See (https://kubernetes.io/docs/reference/workloads-18-19/)
kind: Deployment
metadata:
  name: go-user-store
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: go-user-store
        tier: frontend
    spec:
      containers:
      - name: go-user-store
        image: vahdet/go-user-store:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: USER_STORE_REDIS_URL
          value: redis.default.svc.cluster.local:6379
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 9090
